CREATE TABLE LOG_ASISTENCIA (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    accion VARCHAR2(20),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR2(45),
    detalle VARCHAR2(500)
);

CREATE TABLE LOG_JUSTIFICACION (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    justificacion_id NUMBER,
    accion VARCHAR2(20),
    usuario_admin VARCHAR2(50),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_anterior VARCHAR2(20),
    estado_nuevo VARCHAR2(20)
);

CREATE OR REPLACE TRIGGER trg_log_asistencia
AFTER INSERT OR UPDATE ON ASISTENCIA
FOR EACH ROW
DECLARE
    v_ip VARCHAR2(45) := '127.0.0.1'; -- En producción usarías SYS_CONTEXT
BEGIN
    INSERT INTO LOG_ASISTENCIA (user_id, accion, detalle)
    VALUES (
        :NEW.user_id,
        CASE WHEN :OLD.id IS NULL THEN 'CHECKIN' ELSE 'CHECKOUT' END,
        CASE 
            WHEN :OLD.id IS NULL THEN 'Check-in registrado'
            ELSE 'Check-out registrado'
        END
    );
END;

CREATE OR REPLACE TRIGGER trg_log_justificacion
AFTER INSERT OR UPDATE ON JUSTIFICACION
FOR EACH ROW
BEGIN
    INSERT INTO LOG_JUSTIFICACION (
        justificacion_id, accion, estado_anterior, estado_nuevo
    ) VALUES (
        :NEW.id,
        CASE WHEN :OLD.id IS NULL THEN 'CREACION' ELSE 'APROBACION' END,
        :OLD.estado,
        :NEW.estado
    );
END;

-- Reporte de puntualidad por empleado
CREATE OR REPLACE PROCEDURE sp_reporte_puntualidad_empleado(
    p_username IN VARCHAR2,
    p_desde IN DATE,
    p_hasta IN DATE,
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            u.username,
            a.fecha_registro,
            a.entrada,
            CASE 
                WHEN a.entrada IS NULL THEN 'FALTA'
                WHEN TO_CHAR(a.entrada, 'HH24:MI') > '09:10' THEN 'TARDANZA'
                ELSE 'PUNTUAL'
            END AS estado_puntualidad
        FROM ASISTENCIA a
        JOIN users u ON a.user_id = u.id
        WHERE u.username = p_username
          AND a.fecha_registro BETWEEN p_desde AND p_hasta
        ORDER BY a.fecha_registro;
END;

-- Reporte general por rango de fechas
CREATE OR REPLACE PROCEDURE sp_reporte_asistencia_rango(
    p_desde IN DATE,
    p_hasta IN DATE,
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            u.username,
            COUNT(*) AS total_dias,
            COUNT(CASE WHEN a.entrada IS NOT NULL THEN 1 END) AS dias_asistidos,
            COUNT(CASE WHEN j.id IS NOT NULL AND j.estado = 'APROBADO' THEN 1 END) AS justificaciones_aprobadas
        FROM users u
        LEFT JOIN ASISTENCIA a ON u.id = a.user_id 
            AND a.fecha_registro BETWEEN p_desde AND p_hasta
        LEFT JOIN JUSTIFICACION j ON u.id = j.user_id 
            AND j.fecha BETWEEN p_desde AND p_hasta
        GROUP BY u.username
        ORDER BY u.username;
END;